// USER
export const SWR_USER_REGISTER = 'SWR_USER_REGISTER'
export const SWR_USER_SCORE = 'SWR_USER_SCORE'

// COMPANY
export const SWR_COMPANY = 'SWR_COMPANY'
export const SWR_COMPANY_STATS = 'SWR_COMPANY_STATS'
export const SWR_COMPANY_ADMINS = 'SWR_COMPANY_ADMINS'
